### ISSUE TITLE
UnboundLocalError: local variable 'mod' referenced before assignment

### ISSUE THREAD

**Issue by kevinsmia1939** [Julian-Hochhaus/LG4X-V2#52]
I encounter crash when I press evaluate after press fitting.
I am using the latest git commit.

Python 3.10.10

```
Traceback (most recent call last):
  File "/home/kevin/Desktop/software/LG4X-V2/Python/main.py", line 1844, in eva
    self.ana('eva')
  File "/home/kevin/Desktop/software/LG4X-V2/Python/main.py", line 2890, in ana
    temp_res = self.BGModCreator(x, y, mode=mode)
  File "/home/kevin/Desktop/software/LG4X-V2/Python/main.py", line 2810, in BGModCreator
    temp_res = self.bgSelector(x, y, mode=mode, idx_bg= self.idx_bg[0])
  File "/home/kevin/Desktop/software/LG4X-V2/Python/main.py", line 2126, in bgSelector
    return [mod, bg_mod, pars]
UnboundLocalError: local variable 'mod' referenced before assignment
Aborted (core dumped)

```

I think that in the function bgSelector in main.py,

```
        if idx_bg == 100:
            if mode == "eva":
                shA = self.pre[1][0][1]
                shB = self.pre[1][0][3]
                pars = None
                bg_mod = xpy.shirley_calculate(x, y, shA, shB)
```
The `mod` is not define, so this cause an error.

**Comment by Julian-Hochhaus** [comment]
Problem is hopefully solved with last commits on `dev` branch :) thanks for catching that error!

**Comment by kevinsmia1939** [comment]
Thanks, that fix the issue.
