### ISSUE TITLE
Bug report: Not able to load saved  presets+data 

### ISSUE THREAD

**Issue by Hexanders** [Julian-Hochhaus/LG4X-V2#6]
```
Traceback (most recent call last):
  File "~/LG4X-V2/Python/main.py", line 541, in preset
    self.loadPreset()
  File "~/LG4X-V2/Python/main.py", line 703, in loadPreset
    self.pre = ast.literal_eval(self.pre)
  File "/usr/lib64/python3.10/ast.py", line 62, in literal_eval
    node_or_string = parse(node_or_string.lstrip(" \t"), mode='eval')
  File "/usr/lib64/python3.10/ast.py", line 50, in parse
    return compile(source, filename, mode, flags,
  File "<unknown>", line 5
    ~/FitXPS-LG4X/TestDataSet/33_proc_ML_Deposited@LN2.csv
                                                      ^
SyntaxError: invalid decimal literal
```

**Comment by Julian-Hochhaus** [comment]
Probably this bug is not caused by LG4X itself but rather by `python/ast.py`. I am not sure but I assume that the **@** in the filename could cause this error.

**Comment by Hexanders** [comment]
Yes it is! But not bei @. The file name start with a digit, after presetting a letter in front of the digit the error went away.
