### ISSUE TITLE
main.py:2050: RuntimeWarning: invalid value encountered in divide

### ISSUE THREAD

**Issue by Julian-Hochhaus** [Julian-Hochhaus/LG4X-V2#9]
As documented here #4, invalid values in the calculation of fwhm's are not carefully caught.
 
```
    ~/LG4X-V2/Python/main.py:2050: RuntimeWarning: invalid value encountered in divide
    y_temp = y_area / np.max(y_area)
    Traceback (most recent call last):
    File "~/LG4X-V2/Python/main.py", line 1103, in fit
    self.ana('fit')
    File "~/LG4X-V2/Python/main.py", line 2052, in ana
    fwhm_temp = x_[-1] - x_[0]
    IndexError: list index out of range
```

**Comment by Julian-Hochhaus** [comment]
resolved by bb7ae31
